### ISSUE TITLE
doesn't work on x64 system

### ISSUE THREAD

**Issue by greyfox95** [juliankay/FakeGPS#13]
after downloading the fakegps-master.zip and extracting the folder i set test signing to on and proceeded to device manager. Actions>Add Legacy Hardware>Install Hardware I select Manually From a List>Sensors>Have Disk...; Browse...>...src/FakeGPS.Driver>OK; then it displays a message that reads 
"The folder you specified doesn't contain a compatible software driver for your device. If the folder contains a driver, make sure it is designed to work with Windows for x64-based systems."

**Comment by juliankay** [comment]
Sounds like you're trying to install from the source code rather than the binary. Check the instructions and download the binary at https://github.com/juliankay/FakeGPS/releases
