### ISSUE TITLE
 can't get installed on Windows 64 bit system

### ISSUE THREAD

**Issue by mrchanshares** [juliankay/FakeGPS#14]
I get a message saying
"  The folder you specified doesn't contain a compatible software driver for your device. If the folder contains a driver, make sure it is designed to work with Windows for x64-based systems."
So it can't get installed on Windows 64 bit system. Any solution? Can you compile it in Window 10 64 bit system?

**Comment by juliankay** [comment]
Are you installing from the repository or from the release zip file?

FakeGPS is **only** built for x64 systems.

**Comment by mrchanshares** [comment]
I install the device driver from clone or download at https://github.com/juliankay/FakeGPS

I get the screenshot.
![fakegps](https://user-images.githubusercontent.com/13177915/32202587-c98a2300-be18-11e7-8da2-df84e894cae2.jpg)

**Comment by mrchanshares** [comment]
I try again with
FakeGPS v1.0.0-alpha2

It still fail:
![fake2](https://user-images.githubusercontent.com/13177915/32202603-e0800eda-be18-11e7-8c67-8d5072aae248.jpg)

**Comment by Nikvand** [comment]
I have exact same issue as above. I get "The following hardware was not installed..." message as the screenshot shows.

**Comment by juliankay** [comment]
@Nikvand also x64?

**Comment by Nikvand** [comment]
@juliankay Of course x64

**Comment by supra63200** [comment]
@juliankay I have the same error on a brand new Azure VM on Windows 10 Pro 1709 (x64 of course

**Comment by juliankay** [comment]
Thanks for the information everyone. I've not had a chance to test this on 1709 yet, but I'm going to provision a new VM to work out what's happening.

**Comment by juliankay** [comment]
Interestingly it worked first time when I installed on an existing VM which has 1709 installed, but I'll provision a fresh machine to test there.

![image](https://user-images.githubusercontent.com/952538/32650872-3dc37970-c5f7-11e7-87d6-21f28fc61bf9.png)

**Comment by juliankay** [comment]
Worked first time on a brand new VM running Windows 10 x64 version 1709.

![image](https://user-images.githubusercontent.com/952538/32653013-2facc36c-c5fe-11e7-970b-465f8ae722fe.png)

**Comment by juliankay** [comment]
@supra63200 can you provide repro steps? can you assure me you following the instructions correctly?

**Comment by supra63200** [comment]
* type `bcdedit /set testsigning on` in a Powershell (tried both admin and user)
* Open device manager
* Select the computer
* Click Add legacy Hardware in Action Menu
* Click Next
* Select install the hardware that I manually select from a list (Advanced)
* Select Sensors in the list and click Next
* On page "ready to install click Next
![image](https://user-images.githubusercontent.com/4090365/32655246-1d828bfe-c60d-11e7-9956-b64fdb81295b.png)
* "...Installing..."
* Click Finish
![image](https://user-images.githubusercontent.com/4090365/32655298-4fbdc142-c60d-11e7-8c06-182b303726a5.png)
Fun fact : after the fifth installation it just decided to work (did the exact same steps)
Previously after "..installing..." I had the same window as @mrchanshares

**Comment by juliankay** [comment]
Hmm. Well you need to reboot after turning on test mode, and either reboot or disable/enable the device after installation. If you've rebooted, that might have fixed your issue.

I'm not sure why it says "Fusion Sensor V2" as it says "FakeGPS" for me... bit strange!

Glad you've got it working, hopefully these steps will help other folk too.

**Comment by supra63200** [comment]
No I didn't that's the weird part it just worked after a while, no reboot necessary but it was stuck on the first start error (issue #3 ) even after reboot. So I uninstalled and reinstalled it and now it works perfectly and the name changed to FakeGPS Sensor

**Comment by supra63200** [comment]
Here is the updated walkthrough :
* type `bcdedit /set testsigning` on in a Powershell (Right click on bottm-left corner Windows icon and then click on Windows PowerShell)
* Reboot the computer
* Open device manager (Right click on the Windows icon again and then on Device Manager)
* Click on the computer (First element of the list)
* Click Add legacy Hardware in Action Menu
* Click Next
* Select install the hardware that I manually select from a list (Advanced) and click Next
* Click Next again
* Click on "Have Disk" and then "Browse" and select the FakeGPS.inf from the extracted release archive (in "x64 driver" folder)
* On page "ready to install click Next
* Wait for the installation to complete
* Click on Finish 
* Activate the driver:
 * By rebooting the computer
 * By Disabling the driver and re-enabling it again in the Device Manager(Right click on "FakeGPS Sensor and click Disable/Enable Device)
* Open a PowerShell and navigate to the FakeGPS.exe folder (In the root of the extracted archive)
* Use it by typing .\FakeGPS.exe -g or .\FakeGPS -s lat,long (ex: 1.2,3.4)

**Comment by mrchanshares** [comment]
Why I cannot do this? I am in Windows 10 x 64 Home

PS C:\WINDOWS\system32>  bcdedit /set testsigning
The set command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.

**Comment by juliankay** [comment]
@mrchanshares as per the instructions:

![image](https://user-images.githubusercontent.com/952538/32690175-1ecc6dc6-c6ea-11e7-9fc7-f6749fa7005e.png)

**Comment by mrchanshares** [comment]
Maybe it can only be done on tablet device? My Window 10 is installed on a laptop made 3 years ago without touchscreen.

**Comment by juliankay** [comment]
@mrchanshares I think you probably just need to type the command correctly 🙂

`bcdedit /set testsigning on`

I don't know of any reason why it shouldn't work for you (though I haven't tested it on Windows 10 Home). I think it's just a user error here I'm afraid, I hope you work it out!

**Comment by juliankay** [comment]
Closed as there is no problem installing on Windows 10 x64, but I have opened #17 to track improved documentation.

**Comment by hajuch0** [comment]
why i've this error " Object reference not set to an instance of an object."

**Comment by rangelrmorais** [comment]
> why i've this error " Object reference not set to an instance of an object."

this stopped happening to me after i open the MAPS app for windows and accept the popup. Then i tried FakeGPS -g and voila!

**Comment by DeTodd** [comment]
@rangelrmorais That was it! I have no idea why this would be, I've even used my windows "device gps" in another application without complaint.
