### ISSUE TITLE
Error : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Suleman-Elahi** [juliankay/FakeGPS#15]
On my Windows 10, build: 15063.674 (x64) I got the following error !!!!
-----------------------------------------------------------------------------------------------
C:\Users\ListOfFreeware\Downloads\FakeGPS-v1.0.0-alpha2>FakeGPS -s 25,75
ZOMG, we got this error:
Object reference not set to an instance of an object.
Send feedback plz!
----------------------------------------------------------------------------------------------

Any idea how to fix it ?

**Comment by juliankay** [comment]
What language do you have your operating system set to?

**Comment by Suleman-Elahi** [comment]
The language is set to English(India) as my region is India.

I am afraid that I can't provide you much information. I have gone through the other issues as well and didn't find anything. The same error is showing when I am trying to enter location (in decimal) and in natural number figures !!!!

BTW many thanks for replying !!

**Comment by supra63200** [comment]
Can you try uninstalling and reinstalling the driver and then rebooting, it solved the problem for me
