### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jacobhub** [juliankay/FakeGPS#5]
Set location failed with "Object reference not set to an instance of an object" error.
Version: v1.0.0-alpha2 .
OS: Windows 10 Pro 64-bit .
The driver was installed successfully and get location also worked, but set location failed.

**Comment by jacobhub** [comment]
After restart and install the driver again it works

**Comment by juliankay** [comment]
Hi @jacobhub - yeah I'm tracking this as issue #3 - restarting should fix the issue (as you have discovered). Only happens on the very first run. Shouldn't be hard to fix I just haven't got around to it yet.
