### ISSUE TITLE
Is Window 8.1 supported?

### ISSUE THREAD

**Issue by jacobhub** [juliankay/FakeGPS#6]
Driver installation fails on windows 8.1 64-bit. is it a limitation in the os or a bug ?

**Comment by juliankay** [comment]
I think it should, but I haven't tested it. Currently I have only tested it on Windows 10 x64.

It has been built using the tools for Windows 10, so this may not be backward compatible, I'll need to look into it.

If it does not work, I will be sure to update the documentation to reflect this.

**Comment by juliankay** [comment]
Closed for now as I don't plan on using it on Windows 8.1, so I'm not going to test it.
