### ISSUE TITLE
Trouble during instalation

### ISSUE THREAD

**Issue by xward** [juliankay/FakeGPS#9]
details of the procedure :
- switched to test mode ( bcdedit /set testsigning on) and reboot
- device manager > add legacy hardware > manually install hardware from list > Sensors > Have Disk
- I select the file : \src\FakeGPS.Driver\FakeGPS.inf
- then It prompt me the following :
![errorgps](https://cloud.githubusercontent.com/assets/5379665/16794513/10f9e280-48d0-11e6-8a4c-643d1a98c4e0.png)

Did I miss something ? What is wrong with this procedure ?

notes:
- using windows 10 64bits
- I tried with the branch master and with version 1.0.0-alpha2, same result.

**Comment by juliankay** [comment]
I'll take a look

**Comment by juliankay** [comment]
I've just tested this and can confirm there are no issues using this on a fresh Windows 10 x64.

Are you sure you've extracted the zip correctly?

**Comment by juliankay** [comment]
>I select the file : \src\FakeGPS.Driver\FakeGPS.inf

I've just noticed it looks like you're using the source code, please use the binary release at [https://github.com/juliankay/FakeGPS/releases](https://github.com/juliankay/FakeGPS/releases)

**Comment by xward** [comment]
Indeed ... I didn't saw you had release zips :)

Thanks a lot for your work !
